sftp_s3s:
  #image: chessracer/sftp-s3fs:latest
  build: .
  container_name: klassik-sftp
  ports:
   - "21:22"
  environment:
    AWSACCESSKEYID: ${AWSACCESSKEYID}
    AWSSECRETACCESSKEY: ${AWSSECRETACCESSKEY}
    S3_BUCKET_NAME: ${S3_BUCKET_NAME}
  cap_add:
   - MKNOD
   - SYS_ADMIN
  security_opt:
   - apparmor:unconfined
  devices:
   - /dev/fuse
  #command: ${USERNAME}:${PASSWORD}:::sync_to_s3
  command: ${USERNAME}:${PASSWORD}::1001:sync_to_s3
